mappings:

  mapping_categories:
    'DwellingTypeDescr': 'dwelling'
    'MainSpaceHeatingFuel': ['heating', 'co2_emission']
    'MainWaterHeatingFuel': ['heating', 'co2_emission']
    'VentilationMethod': 'ventilation_ac'
    'HeatSystemControlCat': 'heat_control'
    'ThermalMassCategory': 'termal_mass'
    'PrimaryCircuitLoss': 'primary_loss'

  dwelling:
    "Detached house": "Detached houses"
    "Semi-detached house": "Semi detached"
    "Mid-terrace house": "Mid-terrace"
    "End of terrace house": "End of terrace"
    "Mid-floor apartment": "Apartments"
    "Top-floor apartment": "Apartments"
    "Ground-floor apartment": "Apartments"
    "House": "Detached houses"
    "Maisonette": "Apartments"
    "Apartment": "Apartments"
    "Basement Dwelling": "Apartments"
    null: "Missing"

  heating:
    "Mains Gas": "Mains Gas"
    "Heating Oil": "Heating Oil"
    "Electricity": "Electricity"
    "Solid Multi-Fuel": "Solid Fuel"
    "Bulk LPG (propane or butane)": "LPG"
    "Manufactured Smokeless Fuel": "Manufactured Smokeless Fuel"
    "House Coal": "House Coal"
    "Wood Pellets (bulk supply for": "Wood"
    "Sod Peat": "Other"
    "Bottled LPG": "LPG"
    "Wood Logs": "Wood"
    "Wood Pellets (in bags for seco": "Wood"
    "Peat Briquettes": "Other"
    "Wood Chips": "Wood"
    "Electricity - Off-peak Night-R": "Electricity"
    "Anthracite": "House Coal"
    "Electricity - Standard Domesti": "Electricity"
    "Electricity - On-peak Night-Ra": "Electricity"
    "Biodiesel from renewable sourc": "Biodiesel"
    "Bioethanol from renewable sour": "Bioethanol"
    "None": "Other"
    null: "Missing"

  ventilation_ac:
    'Natural vent.': 0.52
    'Pos input vent.- loft': 0.51
    'Pos input vent.- outside': 0.50
    'Whole house extract vent.': 0.50
    'Bal.whole mech.vent no heat re': 0.70
    'Bal.whole mech.vent heat recvr': 0.70

  heat_control:
    1: 1.2
    2: 0.5
    3: 0
    0: 1.2

  co2_emission:
    "Mains Gas": 0.203
    "Heating Oil": 0.272
    "Solid Fuel": 0.369
    "LPG": 0.232
    "Manufactured Smokeless Fuel": 0.392
    "House Coal": 0.361
    "Wood": 0.025
    "Other": 0.203
    "Electricity": 0.224
    "Biodiesel": 0.047
    "Bioethanol": 0.064
    "Missing": null

  termal_mass:
    "Medium": 0.2
    "Medium-high": 0.32
    "Medium-low": 0.14
    "High": 0.5
    "Low": 0.07

  primary_loss:
    "Electric immersion heater": 0
    "Boiler with uninsulated primar": 1220
    "Boiler with insulated primary": 610
    "Combi boiler": 0
    "CPSU (including electric CPSU)": 0
    "Boiler and thermal store withi": 0
    "Separate boiler and thermal st": 0
    "Community heating": 360
    "None": 0



# Features where missing values should be imputed with average
imputation:
  average:
    - WindowArea
    - WallArea
    - RoofArea
    - DoorArea
    - UValueWindow
    - UValueWall
    - UValueFloor
    - UvalueDoor
    - UValueRoof
    - HSMainSystemEfficiency
    - WHMainSystemEff
    - InsulationThickness
    - WaterStorageVolume
    - HSSupplSystemEff
    - NoOfChimneys
    - NoOfOpenFlues
    - NoOfFansAndVents

  # Features where missing values should be imputed with most frequent value
  most_frequent:
    - SA_Code
    - MainSpaceHeatingFuel
    - MainWaterHeatingFuel
    - SHRenewableResources
    - WHRenewableResources

    - VentilationMethod
    - InsulationType
    - PrimaryCircuitLoss
    - StructureType
    - SupplSHFuel


# Area related features where missing values should be imputed with average 
imputation_area:
  average:
    - WindowArea
    - WallArea
    - RoofArea
    - DoorArea

grant_dwelling_mapping:
  "Detached house": "detached"
  "Semi-detached house": "semi-detached"
  "Mid-terrace house": "mid-terrace"
  "End of terrace house": "houses"
  "Mid-floor apartment": "apartment"
  "Top-floor apartment": "apartment"
  "Ground-floor apartment": "apartment"
  "House": "houses"
  "Maisonette": "apartment"
  "Apartment": "apartment"
  "Basement Dwelling": "apartment"
  null: "houses"

